/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.steinko.plugin

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'org.steinko.plugin.greeting' plugin.
 */
class GreetingPluginFunctionalTest {

   
   // @Test fun `can run task`() {
        // Setup the test build
    //    val projectDir = File("build/functionalTest")
    //    projectDir.mkdirs()
    //    projectDir.resolve("settings.gradle.kt").writeText("")
    //    projectDir.resolve("build.gradle.kt").writeText("""
    //         apply<org.steinko.plugin.GreetingPlugin>()
    //    """)

        // Run the build
    //    val runner = GradleRunner.create()
    //    runner.forwardOutput()
    //    runner.withPluginClasspath()
    //    runner.withArguments("greeting")
    //    runner.withProjectDir(projectDir)
    //    val result = runner.build();

        // Verify the result
    //    assertTrue(result.output.contains("Hello from plugin 'org.steinko.greeting.GreetingPluging'"))
   // }
}
