/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.steinko.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
/**
 * A simple 'hello world' plugin.
 */
class GreetingPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'org.steinko.plugin.greeting'")
            }
        }
    }
}
