/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.steinko.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'org.steinko.plugin.greeting' plugin.
 */
class GreetingPluginTest {
   // @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
   //     val project = ProjectBuilder.builder().build()
   //     project.plugins.apply("org.steinko.plugin.GreetingPlugin")

        // Verify the result
    //    assertNotNull(project.tasks.findByName("greeting"))
    //}
}
